'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resource1
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Grid2PNG.Resource1", GetType(Resource1).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 	//set up xsec
    '''		//add cross section line
    '''		OpenLayers.Renderer.symbol.newnode = [4, 0, 6, 0, 6, 4, 10, 4, 10, 6, 6, 6, 6, 10, 4, 10, 4, 6, 0, 6, 0, 4, 4, 4, 4, 0];
    '''		OpenLayers.Renderer.symbol.move = [0,10, 4,13, 4,11, 9,11 ,9,16, 7,16 ,10,20 ,13,16 ,11,16 ,11,11 ,16,11 ,16,13 ,20,10 ,16,7 ,16,9 ,11,9 ,11,4 ,13,4 ,10,0 ,7,4 ,9,4 ,9,9 ,4,9 ,4,7];
    '''
    '''		Xsec = new OpenLayers.Layer.Vector(&apos;Cross Section&apos;,{styleMap: new OpenLayers.StyleMap({&apos;default&apos;:{strokeColor:  &apos;#000000&apos;,strokeOpacity: 1,strokeWidth: 1,f [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property CompXsec() As String
        Get
            Return ResourceManager.GetString("CompXsec", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property excanvas_min() As Byte()
        Get
            Dim obj As Object = ResourceManager.GetObject("excanvas.min", resourceCulture)
            Return CType(obj,Byte())
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
    '''&lt;head&gt;		
    '''		&lt;script src=&quot;jquery-1.6.2.js&quot;&gt;&lt;/script&gt; 
    '''		&lt;script src=&quot;OpenLayers.js&quot;&gt;&lt;/script&gt;	
    '''		&lt;script src=&quot;excanvas.min.js&quot;&gt;&lt;/script&gt;
    '''		&lt;script src=&quot;jquery.flot.js&quot;&gt;&lt;/script&gt;
    '''		&lt;script src=&quot;jquery.flot.axislabels.js&quot;&gt;&lt;/script&gt;
    '''		&lt;script type=&apos;text/javascript&apos;&gt;
    '''		
    '''			function init() {	
    '''		
    '''
    '''			}
    '''		&lt;/script&gt;
    '''		
    '''		&lt;STYLE type=&apos;text/css&apos;&gt;
    '''		div.olControlMousePosition {
    '''		bottom: 0;
    '''		right: 3px;
    '''		display: block;
    '''		position: absolute;
    '''		font-family: Arial;
    '''		font-size: smal [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property html() As String
        Get
            Return ResourceManager.GetString("html", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
    '''&lt;head&gt;		
    '''		&lt;script src=&quot;VBVAR_PATHjquery-1.6.2.js&quot;&gt;&lt;/script&gt; 
    '''		&lt;script src=&quot;VBVAR_PATHOpenLayers.js&quot;&gt;&lt;/script&gt;	
    '''		&lt;script src=&quot;VBVAR_PATHexcanvas.min.js&quot;&gt;&lt;/script&gt;
    '''		&lt;script src=&quot;VBVAR_PATHjquery.flot.js&quot;&gt;&lt;/script&gt;
    '''		&lt;script src=&quot;VBVAR_PATHjquery.flot.axislabels.js&quot;&gt;&lt;/script&gt;
    '''		&lt;script type=&apos;text/javascript&apos;&gt;
    '''		
    '''			function init() {	
    '''		
    '''
    '''			}
    '''		&lt;/script&gt;
    '''		
    '''		&lt;STYLE type=&apos;text/css&apos;&gt;
    '''		div.olControlMousePosition {
    '''		bottom: 0;
    '''		right: 3px;
    '''		display: block;
    '''		position: a [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property html2() As String
        Get
            Return ResourceManager.GetString("html2", resourceCulture)
        End Get
    End Property
    
    Friend Shared ReadOnly Property jquery_1_6_2() As Byte()
        Get
            Dim obj As Object = ResourceManager.GetObject("jquery-1.6.2", resourceCulture)
            Return CType(obj,Byte())
        End Get
    End Property
    
    Friend Shared ReadOnly Property jquery_flot() As Byte()
        Get
            Dim obj As Object = ResourceManager.GetObject("jquery.flot", resourceCulture)
            Return CType(obj,Byte())
        End Get
    End Property
    
    Friend Shared ReadOnly Property jquery_flot_axislabels() As Byte()
        Get
            Dim obj As Object = ResourceManager.GetObject("jquery.flot.axislabels", resourceCulture)
            Return CType(obj,Byte())
        End Get
    End Property
    
    Friend Shared ReadOnly Property OpenLayers() As Byte()
        Get
            Dim obj As Object = ResourceManager.GetObject("OpenLayers", resourceCulture)
            Return CType(obj,Byte())
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 	//set up xsec
    '''		//add cross section line
    '''		OpenLayers.Renderer.symbol.newnode = [4, 0, 6, 0, 6, 4, 10, 4, 10, 6, 6, 6, 6, 10, 4, 10, 4, 6, 0, 6, 0, 4, 4, 4, 4, 0];
    '''		OpenLayers.Renderer.symbol.move = [0,10, 4,13, 4,11, 9,11 ,9,16, 7,16 ,10,20 ,13,16 ,11,16 ,11,11 ,16,11 ,16,13 ,20,10 ,16,7 ,16,9 ,11,9 ,11,4 ,13,4 ,10,0 ,7,4 ,9,4 ,9,9 ,4,9 ,4,7];
    '''
    '''		Xsec = new OpenLayers.Layer.Vector(&apos;Cross Section&apos;,{styleMap: new OpenLayers.StyleMap({&apos;default&apos;:{strokeColor:  &apos;#000000&apos;,strokeOpacity: 1,strokeWidth: 1,f [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property SimpXsec() As String
        Get
            Return ResourceManager.GetString("SimpXsec", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to function updateVBGRIDNO() {
    '''//new GC
    '''//incase last call crashed
    '''tot1VBGRIDNO=0;
    '''ScriptsNeededVBGRIDNO = new Array();
    '''ELEVarrayVBGRIDNO  = new Array(); //added for multipart
    '''
    '''VBVAR_COMPLEX
    '''
    '''//NEW GC 
    '''//for each XY in array cycle through them and put the required script file in a list 
    '''ELEVarrayVBGRIDNO  = new Array();
    '''//use chainages from first grid
    '''for  (h=0; h&lt;ELEVarray.length; h++){
    '''ELEVarrayVBGRIDNO[h] = new Array(1);
    '''ELEVarrayVBGRIDNO[h][0] = ELEVarray[h][0];
    '''}
    '''
    '''for (h=0; h&lt;ELEVarrayVB [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property UpdateBlock() As String
        Get
            Return ResourceManager.GetString("UpdateBlock", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to //variables to populate from VB
    '''	var minXVBGRIDNO = VBVAR_minX;
    '''	var maxXVBGRIDNO = VBVAR_maxX; 
    '''	var minYVBGRIDNO = VBVAR_minY; 
    '''	var maxYVBGRIDNO = VBVAR_maxY;
    '''	var bmpXVBGRIDNO = VBVAR_bmpX;
    '''	var bmpYVBGRIDNO = VBVAR_bmpY;
    '''	
    '''	//NEW GC moved 
    '''	//grid info
    '''		var llxVBGRIDNO = minXVBGRIDNO; //get from VB
    '''		var llyVBGRIDNO =minYVBGRIDNO; //get from VB
    '''		var cellsizeVBGRIDNO = VBVAR_cellsize; //get from VB
    '''		var gridsizeVBGRIDNO = VBVAR_gridsize; //get from VB
    '''		var intervalsVBGRIDNO = VBVAR_int [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property varBlock() As String
        Get
            Return ResourceManager.GetString("varBlock", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to // *** multipart - xsec
    '''var xsec_length = map.layers[2].features[0].geometry.getLength();
    '''var xsec_done_length = 0;
    '''var xsec_running_total = 0;
    '''var xsec_control = map.controls[6];
    '''interval = xsec_length / intervals;
    '''var Xarray  = new Array();
    '''var Yarray  = new Array();
    '''XYarray2 = new Array();
    '''var xyarray_count = 0;
    '''
    '''
    '''var xsec_remainder = 0;//added for multipart
    '''var cum_xsec_remainder = 0;
    '''for(var vert = 0;vert&lt;xsec_control.vertices.length-1;vert++){
    '''	//get first 2 matching points
    '''	var p1 = x [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property Xcomplex() As String
        Get
            Return ResourceManager.GetString("Xcomplex", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to var num_seg_intervals = seg_length / intervals;
    '''var rise =  y2 - y1;
    '''var run =  x2 - x1;
    '''
    '''var nX = run / num_seg_intervals;
    '''var nY = rise / num_seg_intervals;
    '''
    '''var fullXY = new Array();
    '''
    '''fullXY[0] =  x1 + (nX * interval); 
    '''fullXY[1] = y1 + (nY * interval);
    '''
    '''
    '''return fullXY;.
    '''</summary>
    Friend Shared ReadOnly Property XcomplexXY() As String
        Get
            Return ResourceManager.GetString("XcomplexXY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ELEVarray  = new Array(); //added for multipart
    '''var xsec_remainder = 0;//added for multipart
    '''
    '''//may need to change to find right layer
    '''x1 = map.layers[2].features[0].geometry.components[0].x 
    '''y1 = map.layers[2].features[0].geometry.components[0].y
    '''x2 = map.layers[2].features[0].geometry.components[1].x 
    '''y2 = map.layers[2].features[0].geometry.components[1].y 
    '''
    '''run = x2 - x1;
    '''rise = y2 - y1;
    '''//good ol&apos; pythagerous
    '''total_length = Math.sqrt((Math.pow(rise,2) + Math.pow(run,2)));
    '''
    '''angle = (Math.at [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property Xsimple() As String
        Get
            Return ResourceManager.GetString("Xsimple", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 
    '''var nX ;
    '''if (x1 &lt; x2) {nX = x2 - x1} else {nX = x1 - x2}
    '''var nY;
    '''if (y1 &lt; y2) {nY = y2 - y1} else {nY = y1 - y2}
    '''nX = (nX / intervals) * interval;
    '''nY = (nY / intervals) * interval;
    '''
    '''var fullXY = new Array();
    '''var minX, minY;
    '''if (x1 &lt; x2) {minX = x1} else {minX = x2}
    '''if (y1 &lt; y2) {minY = y1} else {minY = y2}
    '''if (angle &lt; 0) {if (x1 &lt; x2) {minX = x2} else {minX = x1}}
    '''
    '''//if angle is -&apos;ve and between 0 &amp; -90 then 
    '''if (angle &lt; 0 &amp;&amp; angle &gt; -90){fullXY[0] =  minX - nX; fullXY[1] = minY + nY;}
    '''//if [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property XsimpleXY() As String
        Get
            Return ResourceManager.GetString("XsimpleXY", resourceCulture)
        End Get
    End Property
End Class
